security:
  oauth2:
    client:
      clientId: ${GOOGLE_CLIENTE_ID}
      clientSecret: ${GOOGLE_CLIENTE_SECRET}
      accessTokenUri: https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope:
        - profile
        - email
    resoure:
      userInfoUri: https://www.googleapis.com/userinfo/v2/me
      preferTokenInfo: false